# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u1uZSVUxBrnIYOfr_u2Y_uiN_sTHFINX
"""

folder_path = "/content"

!pip install python-docx sentence-transformers faiss-cpu

from docx import Document
import os
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

# Function to read all Word files from the folder
def load_documents(folder_path):
    docs = []
    for filename in os.listdir(folder_path):
        if filename.endswith(".docx"):
            path = os.path.join(folder_path, filename)
            doc = Document(path)
            text = "\n".join([para.text.strip() for para in doc.paragraphs if para.text.strip()])
            docs.append({"text": text, "source": filename})
    return docs

# Load the documents
raw_documents = load_documents(folder_path)
print(f"✅ Loaded {len(raw_documents)} documents.")

# Break each document into smaller chunks (~150 words)
def chunk_document(doc, max_words=150):
    chunks = []
    words = doc["text"].split()
    for i in range(0, len(words), max_words):
        chunk = " ".join(words[i:i+max_words])
        chunks.append({"chunk": chunk, "source": doc["source"]})
    return chunks

# Apply chunking to all documents
all_chunks = []
for doc in raw_documents:
    all_chunks.extend(chunk_document(doc))

print(f"✅ Created {len(all_chunks)} total chunks.")

# Load the sentence transformer model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Create vector embeddings from the chunked text
texts = [chunk["chunk"] for chunk in all_chunks]
embeddings = model.encode(texts, show_progress_bar=True)

# Step 6: Store embeddings in FAISS index
d = embeddings.shape[1]  # dimension of embedding
index = faiss.IndexFlatL2(d)  # create a flat (CPU-based) index
index.add(np.array(embeddings))  # add embeddings to the index

print(f"✅ FAISS index contains {index.ntotal} vectors.")

# Step 7: Define retrieval function
def retrieve(query, k=3):
    query_vec = model.encode([query])
    D, I = index.search(np.array(query_vec), k)  # search top-k
    results = [all_chunks[i] for i in I[0]]
    return results

# Step 8: Try a test question
test_query = "Can residents smoke inside the building?"
results = retrieve(test_query)

# Show results
for i, res in enumerate(results):
    print(f"\n--- Result {i+1} (Source: {res['source']}) ---\n{res['chunk'][:500]}")